import { redirect } from 'next/navigation';

// This page immediately redirects to the API route handler
// which renders a full HTML response with approve/deny result
interface Props {
  params: Promise<{ token: string }>;
  searchParams: Promise<{ action?: string }>;
}

export default async function AdminApprovePage({ params, searchParams }: Props) {
  const { token } = await params;
  const { action } = await searchParams;

  // Show a simple confirmation page with approve/deny buttons if no action taken
  if (!action) {
    return (
      <div className="min-h-screen bg-verint-gradient flex items-center justify-center px-4">
        <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full text-center">
          <div className="text-4xl mb-4">🔑</div>
          <h2 className="text-xl font-bold text-verint-purple-dark mb-3">
            Admin Approval Portal
          </h2>
          <p className="text-gray-500 text-sm mb-8">
            Review and take action on this user access request.
          </p>
          <div className="flex gap-4 justify-center">
            <a
              href={`/api/admin/approve?token=${token}&action=approve`}
              className="flex-1 bg-green-600 hover:bg-green-700 text-white font-bold
                         py-3 px-6 rounded-xl transition-colors text-center"
            >
              ✓ Approve
            </a>
            <a
              href={`/api/admin/approve?token=${token}&action=deny`}
              className="flex-1 bg-red-600 hover:bg-red-700 text-white font-bold
                         py-3 px-6 rounded-xl transition-colors text-center"
            >
              ✗ Deny
            </a>
          </div>
          <p className="text-xs text-gray-400 mt-6">
            This link was generated by the Verint FI Intelligence platform.
          </p>
        </div>
      </div>
    );
  }

  // Redirect to API handler
  redirect(`/api/admin/approve?token=${token}&action=${action}`);
}
